apiVersion: v1
kind: Service
metadata:
  name: jgroups-dns-ping
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 7600
