apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9990"
    spec:
      containers:
      - name: keycloak
        image: yolean/keycloakx
        args:
        # Development with 1 replicas
        - --cluster=local
        env:
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: sqlpassword
        - name: KC_DB_URL_HOST
          value: mysql:3306
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_URL_PROPERTIES
          value: characterEncoding=UTF-8
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 9990
        - name: jgroups-tcp
          containerPort: 7600
        readinessProbe:
          httpGet:
            path: /auth/
            port: 8080
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
          limits:
            cpu: 400m
            memory: 400Mi
        volumeMounts:
        - name: keycloak-conf
          mountPath: /opt/keycloak.x/conf
      volumes:
      - name: keycloak-conf
        configMap:
          name: keycloak-conf
